### ISSUE TITLE
Use on CLI?

### ISSUE THREAD

**Issue by brianblakely** [doesdev/rollup-analyzer#2]
Would be nice to be able to run from CLI.  I normally run rollup itself that way, and am only using rollup in a script to accommodate rollup-analyzer.

**Comment by doesdev** [comment]
Yep, sounds like a sensible thing to add. Let me see what I can come up with.

**Comment by doesdev** [comment]
https://github.com/doesdev/rollup-analyzer-plugin

There's part one of the solution. Next up is a config module, so that (if you weren't using a config otherwise) it can be passed as `rollup -c node:rollup-analyzer-config -f cjs -o index.js module.js`. That should roll out tomorrow.

**Comment by doesdev** [comment]
Thanks for the suggestion, I honestly hadn't made much (any) use of rollup configs before, since most of the builds I was rolling had allot of other stuff going on so I did it all in a script. They are quite pleasant, especially for smaller projects like these modules. No need in a build script to transform one file to cjs.

Anyway, cli is implemented as a plugin and config module that you can use for bundling without a script. Let me know if there's anything I missed with that approach, but I'm going to close this for now. You can see the new modules in the readme.

**Comment by brianblakely** [comment]
`rollup-analyzer-config` blended perfectly into my toolchain.  Thank you for your work.
